### ISSUE TITLE
Making the project eligible for hacktoberfest

### ISSUE THREAD

**Issue by muchirijane** [Code-Dabblers/Ecommerce-Site#12]
**Is your feature request related to a problem? Please describe.**
Currently, the project is not eligible for the Hacktoberfest, it would be great to include this project with other amazing global open source projects.

**Describe the solution you'd like**
Add tags like hacktoberfest, hacktoberfest2020 to the repository. 

**Describe alternatives you've considered**
Apparently, there are no alternatives to solve this issue. 

**Additional context**
No

**Comment by fabcodingzest** [comment]
Thanks for the help, I added some tags in the r :+1: o :)

**Comment by muchirijane** [comment]
Awesome it looks great 🥇
