### ISSUE TITLE
Code the Homepage for the site.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/Ecommerce-Site#23]
**Feature - Landing page for the app**
Work on making the Homepage for the app.

**Describe the solution you'd like**
* Right now we don't have the home page, refer to the design and code it in the `src/JavaScript/modules/homepage.js`.
* For styles the project is using sass, you can refer to these [docs](https://sass-lang.com/guide),  [this tutorial](https://www.youtube.com/watch?v=Zz6eOVaaelI) or [freecodecamp sass module](https://www.freecodecamp.org/learn/front-end-libraries/sass/) in case you are not familiar with it. You can do it!
* Here is the [Figma Design File](https://www.figma.com/file/Zzg4DDmQ4FGgn177VbezcF/Fillyourcart?node-id=0%3A1) you should refer for design (some things are still being edited but the homepage is ready).

**Additional context**
**We are building this app as a Single-page Application so Nav and Footer are to be coded in `src/index.html` and other files are to be coded in `src/JavaScript/modules/` in the lit-html html function in template string, look at the existing examples.**
Feel free to create other modules in the `modules` folder and you can import them into the main module to use in template strings.

Feel free to ask any questions :smile: 
All the best, You got this!

**Comment by hajarNasr** [comment]
Hey, Fab! So could you, please, assign me this issue?

**Comment by fabcodingzest** [comment]
Sure, Happy Coding :grinning:

**Comment by muchirijane** [comment]
Hey, Fab. I will help @hajarNasr with the responsive part. From turning the mobile version into a desktop version. 👍🏽

**Comment by fabcodingzest** [comment]
Sure @muchirijane
All the besttttt
