### ISSUE TITLE
Make the footer of the app responsive.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/Ecommerce-Site#30]
**Make the footer of the app responsive for bigger screen sizes**

We are following mobile first approach for design so the footer right now is just for mobile size, make it responsive (refer to [this](https://www.figma.com/file/Zzg4DDmQ4FGgn177VbezcF/Fillyourcart?node-id=0%3A1) for design file)  for other sizes too. As the app is SPA, the footer code will be in `src/index.html` and the style code in `src/styles/layout/_footer.scss`. Make sure to check the mixins in `src/styles/abstract/_mixin.scss` and read [style Guidelines](https://github.com/Code-Dabblers/Ecommerce-Site/blob/main/style-guidelines.md) to use media queries.

Don't forget to follow [Contribution guidelines](https://github.com/Code-Dabblers/Ecommerce-Site/blob/main/Contribution.md), otherwise PR wont be accepted.

Feel free to ask any questions, All the best :+1:

**Comment by PuneetDhingraA** [comment]
I'll make it responsive......you can assign me🙌🙌

**Comment by fabcodingzest** [comment]
Good Luck @PuneetDhingraA
