### ISSUE TITLE
Code the Error 404 page.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/Ecommerce-Site#31]
**Code the error 404 page**

For design reference check [this file ](https://www.figma.com/file/Zzg4DDmQ4FGgn177VbezcF/Fillyourcart?node-id=0%3A1) and code just the Error 404 page.

You have to code in `src/JavaScript/error404.js` file and for scss you can work on `src/styles/pages/_error.scss` , explore the styles folder and see whats happening and do check already present mixins, variables before you make your own. Follow [style guidelines](https://github.com/Code-Dabblers/Ecommerce-Site/blob/main/style-guidelines.md) for media query as we are using mixins for that too.

Follow [contribution guidelines](https://github.com/Code-Dabblers/Ecommerce-Site/blob/main/Contribution.md) in order to get ur PR accepted.

All the best!

**Comment by sruthiragupathy** [comment]
Hi, please assign this to me.

**Comment by fabcodingzest** [comment]
sure @sruthiragupathy , All the best!
