### ISSUE TITLE
Responsiveness of Cart page.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/Ecommerce-Site#37]
- Code up media queries for the product list page inside (`src/styles/sass/pages/_cart.scss`) so the page **is responsive** exactly the way they do in our [figma](https://www.figma.com/file/bVBi1QpqdSjuFCuOwPqNen/E-comm-App-Kit-(Community)?node-id=0%3A1) design file. Refer to it.
- Don't forget to use media queries by including an **already defined mixin** from (`src/styles/sass/abstracts/_mixins.scss`) and as always, follow **mobile-first approach**.
- Make sure to test the design to check it doesn't break on any screen sizes.

**All the best! 😃 👍**

**Comment by itworks-karen** [comment]
Hey Fab! I'd like to work on the cart's page responsiveness. May I? Thanks!

**Comment by fabcodingzest** [comment]
Sure @itworks-karen !

**Comment by fabcodingzest** [comment]
@itworks-karen can you please use align the items in the product list on cart page.
The image and text are not aligned for all sizes right now , and same is happening with x sign with unit price.

**Comment by itworks-karen** [comment]
Okay, sure!
